/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cabinetmedical.ui;

import com.cabinetmedical.utils.SessionManager;

/**
 *
 * @author Moe_k
 */
public class MedecinDashboard extends javax.swing.JFrame {

    // ID du médecin connecté
    private int medecinId;
    private SessionManager sessionManager;
    
    /**
     * Creates new form MedecinDashboard
     */
    public MedecinDashboard() {
        sessionManager = SessionManager.getInstance();
        initComponents();
        setTitle("Cabinet Medical - Espace Medecin");
        setSize(450, 450);
        setLocationRelativeTo(null);
        
        // Configurer le timeout de session
        sessionManager.setTimeoutCallback(() -> {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Votre session a expire. Veuillez vous reconnecter.", 
                "Session expiree", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            sessionManager.endSession();
            this.dispose();
            new LoginFrame().setVisible(true);
        });
        
        // Logger l'ouverture du dashboard
        sessionManager.logAction("NAVIGATION", "Ouverture du dashboard medecin");
    }
    
    /**
     * Constructeur avec l'ID du médecin
     * @param userId ID du médecin connecté
     */
    public MedecinDashboard(int userId) {
        this();
        this.medecinId = userId;
    }
    
    /**
     * Retourne l'ID du médecin connecté
     * @return medecinId
     */
    public int getMedecinId() {
        return medecinId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        btnGestionPatients = new javax.swing.JButton();
        btnGestionConsultations = new javax.swing.JButton();
        btnBilan = new javax.swing.JButton();
        btnStatistiques = new javax.swing.JButton();
        btnDeconnexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitre.setFont(new java.awt.Font("Segoe UI", 1, 24));
        lblTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitre.setText("Espace Medecin");

        btnGestionPatients.setBackground(new java.awt.Color(33, 150, 243));
        btnGestionPatients.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnGestionPatients.setText("Gestion Patients");
        btnGestionPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionPatientsActionPerformed(evt);
            }
        });

        btnGestionConsultations.setBackground(new java.awt.Color(76, 175, 80));
        btnGestionConsultations.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnGestionConsultations.setText("Gestion Consultations");
        btnGestionConsultations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionConsultationsActionPerformed(evt);
            }
        });

        btnBilan.setBackground(new java.awt.Color(255, 193, 7));
        btnBilan.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnBilan.setText("Bilan Mensuel");
        btnBilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBilanActionPerformed(evt);
            }
        });

        btnStatistiques.setBackground(new java.awt.Color(156, 39, 176));
        btnStatistiques.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnStatistiques.setText("Statistiques");
        btnStatistiques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatistiquesActionPerformed(evt);
            }
        });

        btnDeconnexion.setBackground(new java.awt.Color(244, 67, 54));
        btnDeconnexion.setFont(new java.awt.Font("Segoe UI", 1, 14));
        btnDeconnexion.setText("Deconnexion");
        btnDeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionConsultations, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBilan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatistiques, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnGestionPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnGestionConsultations, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnBilan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(btnStatistiques, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnDeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionPatientsActionPerformed
        new GestionPatientsFrame().setVisible(true);
    }//GEN-LAST:event_btnGestionPatientsActionPerformed

    private void btnGestionConsultationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionConsultationsActionPerformed
        new GestionConsultationsFrame(medecinId).setVisible(true);
    }//GEN-LAST:event_btnGestionConsultationsActionPerformed

    private void btnBilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBilanActionPerformed
        sessionManager.updateActivity();
        sessionManager.logAction("NAVIGATION", "Ouverture Bilan Mensuel");
        new BilanFrame().setVisible(true);
    }//GEN-LAST:event_btnBilanActionPerformed

    private void btnStatistiquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatistiquesActionPerformed
        sessionManager.updateActivity();
        sessionManager.logAction("NAVIGATION", "Ouverture Statistiques");
        new StatistiquesFrame().setVisible(true);
    }//GEN-LAST:event_btnStatistiquesActionPerformed

    private void btnDeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnexionActionPerformed
        sessionManager.endSession();
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnDeconnexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedecinDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedecinDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedecinDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedecinDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedecinDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBilan;
    private javax.swing.JButton btnDeconnexion;
    private javax.swing.JButton btnGestionConsultations;
    private javax.swing.JButton btnGestionPatients;
    private javax.swing.JButton btnStatistiques;
    private javax.swing.JLabel lblTitre;
    // End of variables declaration//GEN-END:variables
}
